### ISSUE TITLE
Enable an accounting check-and-balance that insures that what’s reported as collected by the machine is in fact what has been collected by the Maintainer. 

### ISSUE THREAD

**Issue by jack-le-nus** [huazhihao/SCMWorkshop2#1]
In a recent enhancement (last of the eight done recently), each time “Press to Collect Cash” is
pressed, a record that contains the amount collected and the logged in Maintainer’s id is
captured and recorded in a central database.
It was later uncovered, however, that what has been recorded by the system often does not
always tally with what the Maintainer submits as collected. The maintainer often complains
that it is frustrating and time-consuming to manually calculate these amounts; some have given
up calculating and others insist that the system displays erroneous amounts than what’s
physically collected.
An enhancement is identified to address this problem and especially to aid the Maintainer. The
system is required to provide an at-a-glance display of the cash amount available, by
denomination, for collection by the Maintainer. This will enable the Maintainer to readily tally
the total cash collected and the total number of coins by denomination displayed in “Show
Total Cash Held” and “Press to Collect Cash” when pressed, thus leaving no room for dispute
over system errors.

**Comment by jack-le-nus** [comment]
I verified and tested. Can release

**Comment by rahulnusiss** [comment]
Integration tests already completed.
Tested on production environment for R1.0.9.
Enhancement accepted. Closing this ticket.
