### ISSUE TITLE
Reset the values to null for “Show Total Cash Held” and “Press to Collect Cash” when the Maintainer successfully pushes “Press Here When Finished”. 

### ISSUE THREAD

**Issue by jack-le-nus** [huazhihao/SCMWorkshop2#2]
The simulation currently does
not clear the values on the completion of a Maintenance session. Upon a subsequent re-login
to the Maintenance Panel in the same session, the cash previously held and already collected,
persists in display. This sometimes causes confusion to Maintainer.

**Comment by rahulnusiss** [comment]
Add necessary comments to the code.

**Comment by jack-le-nus** [comment]
I verified and tested. Can release

**Comment by rahulnusiss** [comment]
Integration tests already completed.
Tested on production environment for R1.0.9.
Bug-Fix accepted. Closing this issue.
